version = "2.0"
extensions_dir = "modules/"
logs_dir = "logs/"
title = "LoadAvg"
timezone = "America/New_York"
daystokeep = "30"
allow_anyone = "false"
chart_type = "24"
username = ""
password = ""
https = "false"
checkforupdates = "false"
apiserver = "false"
logger_interval = '5'
[api]
url = ""
key = ""
username = ""
server = ""
[network_interface]
[modules]
Apache = "false"
Cpu = "true"
Disk = "true"
Memory = "true"
Network = "true"
Server = "true"
